"""create_clients_table

Revision ID: 59025876a749
Revises: d670ccb3cf50
Create Date: 2024-12-03 09:59:47.286320

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '59025876a749'
down_revision: Union[str, None] = 'd670ccb3cf50'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clients',
                    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
                    sa.Column('name', sa.String(), nullable=False),
                    sa.Column('code', sa.String(), nullable=False),
                    sa.Column('contact_person_name', sa.String(), nullable=False),
                    sa.Column('contact_person_email', sa.String(), nullable=False),
                    sa.Column('country_id', sa.UUID(), nullable=False),
                    sa.Column('address', sa.String(), nullable=False),
                    sa.Column('phone_number', sa.String(), nullable=False),
                    sa.Column('description', sa.String(), nullable=True),
                    sa.Column('logo_url', sa.String(), nullable=True),
                    sa.Column('auth0_id', sa.String(), nullable=True),
                    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
                    sa.Column('created_by', sa.UUID(), nullable=True),
                    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
                    sa.Column('updated_by', sa.UUID(), nullable=True),
                    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('code'),
                    sa.UniqueConstraint('contact_person_email')
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('clients')
    # ### end Alembic commands ###
