"""add_ufc5_stat_tables

Revision ID: 5ebc4f2efb75
Revises: ca572f472f90
Create Date: 2026-03-07 03:47:35.962288

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5ebc4f2efb75'
down_revision: Union[str, Sequence[str], None] = 'ca572f472f90'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fact_ufc5_perk_state',
    sa.Column('fighter_id', sa.UUID(), nullable=False),
    sa.Column('as_of_date', sa.Date(), nullable=False),
    sa.Column('perk_key', sa.String(length=32), nullable=False),
    sa.Column('perk_score', sa.Numeric(precision=8, scale=4), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('consecutive_above', sa.SmallInteger(), server_default=sa.text('0'), nullable=False),
    sa.Column('consecutive_below', sa.SmallInteger(), server_default=sa.text('0'), nullable=False),
    sa.ForeignKeyConstraint(['fighter_id'], ['dim_fighter.fighter_id'], ),
    sa.PrimaryKeyConstraint('fighter_id', 'as_of_date', 'perk_key')
    )
    op.create_index('ix_ufc5_perk_fighter_date', 'fact_ufc5_perk_state', ['fighter_id', sa.literal_column('as_of_date DESC')], unique=False)
    op.create_table('fact_ufc5_stat_snapshot',
    sa.Column('fighter_id', sa.UUID(), nullable=False),
    sa.Column('as_of_date', sa.Date(), nullable=False),
    sa.Column('accuracy', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('blocking', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('footwork', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('head_movement', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('kick_power', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('kick_speed', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('punch_power', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('punch_speed', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('takedown_defence', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('bottom_game', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('clinch_grapple', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('clinch_striking', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('ground_striking', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('submission_defence', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('submission_offence', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('takedowns', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('top_game', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('body_strength', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('cardio', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('chin_strength', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('legs_strength', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('recovery', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('standup_overall', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('grappling_overall', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('health_overall', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('base_overall', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('synergy_bonus', sa.Numeric(precision=6, scale=3), nullable=False),
    sa.Column('perk_bonus', sa.Numeric(precision=6, scale=3), nullable=False),
    sa.Column('effective_overall', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('mma_fight_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('tier_a_fight_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('total_fights', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('division_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['division_id'], ['dim_division.division_id'], ),
    sa.ForeignKeyConstraint(['fighter_id'], ['dim_fighter.fighter_id'], ),
    sa.PrimaryKeyConstraint('fighter_id', 'as_of_date')
    )
    op.create_index('ix_ufc5_snapshot_fighter_date', 'fact_ufc5_stat_snapshot', ['fighter_id', sa.literal_column('as_of_date DESC')], unique=False)
    op.create_table('fact_ufc5_stat_delta',
    sa.Column('bout_id', sa.UUID(), nullable=False),
    sa.Column('fighter_id', sa.UUID(), nullable=False),
    sa.Column('pre_overall', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('post_overall', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('delta_overall', sa.Numeric(precision=6, scale=3), nullable=False),
    sa.Column('tier_used', sa.String(length=1), nullable=False),
    sa.Column('stat_deltas_json', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('perk_deltas_json', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.CheckConstraint("tier_used IN ('A', 'B', 'C')", name='ck_fact_ufc5_stat_delta_tier'),
    sa.ForeignKeyConstraint(['bout_id'], ['fact_bout.bout_id'], ),
    sa.ForeignKeyConstraint(['fighter_id'], ['dim_fighter.fighter_id'], ),
    sa.PrimaryKeyConstraint('bout_id', 'fighter_id')
    )
    op.create_index('ix_ufc5_delta_fighter', 'fact_ufc5_stat_delta', ['fighter_id', 'bout_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_ufc5_delta_fighter', table_name='fact_ufc5_stat_delta')
    op.drop_table('fact_ufc5_stat_delta')
    op.drop_index('ix_ufc5_snapshot_fighter_date', table_name='fact_ufc5_stat_snapshot')
    op.drop_table('fact_ufc5_stat_snapshot')
    op.drop_index('ix_ufc5_perk_fighter_date', table_name='fact_ufc5_perk_state')
    op.drop_table('fact_ufc5_perk_state')
    # ### end Alembic commands ###
