"""Add tapology_link and stats_link to fighters

Revision ID: a1b2c3d4e5f6
Revises: d7e3f3322075
Create Date: 2025-10-23 00:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a1b2c3d4e5f6'
down_revision: Union[str, None] = 'd7e3f3322075'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fighters', sa.Column('tapology_link', sa.Text(), nullable=True))
    op.add_column('fighters', sa.Column('stats_link', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('fighters', 'stats_link')
    op.drop_column('fighters', 'tapology_link')
    # ### end Alembic commands ###
