"""Add tables

Revision ID: d7e3f3322075
Revises: d670ccb3cf50
Create Date: 2025-10-21 15:34:55.208052

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd7e3f3322075'
down_revision: Union[str, None] = 'd670ccb3cf50'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fighters',
    sa.Column('fighter_id', sa.String(length=16), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('entry_elo', sa.Integer(), nullable=True),
    sa.Column('current_elo', sa.Integer(), nullable=True),
    sa.Column('peak_elo', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('fighter_id')
    )
    op.create_table('promotions',
    sa.Column('promotion_id', sa.UUID(as_uuid=False), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('link', sa.Text(), nullable=True),
    sa.Column('strength', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.PrimaryKeyConstraint('promotion_id')
    )
    op.create_table('events',
    sa.Column('event_id', sa.UUID(as_uuid=False), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('event_date', sa.Date(), nullable=False),
    sa.Column('event_link', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('event_id')
    )
    op.create_table('pre_ufc_bouts',
    sa.Column('bout_id', sa.UUID(as_uuid=False), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('fighter_id', sa.String(length=16), nullable=True),
    sa.Column('promotion_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('result', sa.String(), nullable=True),
    sa.CheckConstraint("result IN ('win', 'loss', 'draw', 'nc')"),
    sa.ForeignKeyConstraint(['fighter_id'], ['fighters.fighter_id'], ),
    sa.ForeignKeyConstraint(['promotion_id'], ['promotions.promotion_id'], ),
    sa.PrimaryKeyConstraint('bout_id')
    )
    op.create_table('bouts',
    sa.Column('bout_id', sa.String(length=16), nullable=False),
    sa.Column('event_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('is_title_fight', sa.Boolean(), nullable=True),
    sa.Column('method', sa.String(), nullable=True),
    sa.Column('round_num', sa.Integer(), nullable=True),
    sa.Column('time_sec', sa.Integer(), nullable=True),
    sa.Column('time_format', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['events.event_id'], ),
    sa.PrimaryKeyConstraint('bout_id')
    )
    op.create_table('bout_participants',
    sa.Column('bout_id', sa.String(length=16), nullable=False),
    sa.Column('fighter_id', sa.String(length=16), nullable=False),
    sa.Column('outcome', sa.String(), nullable=False),
    sa.CheckConstraint("outcome IN ('win', 'loss', 'draw', 'nc')"),
    sa.Column('kd', sa.Integer(), nullable=True),
    sa.Column('sig_strikes', sa.Integer(), nullable=True),
    sa.Column('sig_strikes_thrown', sa.Integer(), nullable=True),
    sa.Column('total_strikes', sa.Integer(), nullable=True),
    sa.Column('total_strikes_thrown', sa.Integer(), nullable=True),
    sa.Column('td', sa.Integer(), nullable=True),
    sa.Column('td_attempts', sa.Integer(), nullable=True),
    sa.Column('sub_attempts', sa.Integer(), nullable=True),
    sa.Column('reversals', sa.Integer(), nullable=True),
    sa.Column('control_time_sec', sa.Integer(), nullable=True),
    sa.Column('head_ss', sa.Integer(), nullable=True),
    sa.Column('body_ss', sa.Integer(), nullable=True),
    sa.Column('leg_ss', sa.Integer(), nullable=True),
    sa.Column('distance_ss', sa.Integer(), nullable=True),
    sa.Column('clinch_ss', sa.Integer(), nullable=True),
    sa.Column('ground_ss', sa.Integer(), nullable=True),
    sa.Column('strike_accuracy', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('elo_before', sa.Integer(), nullable=True),
    sa.Column('elo_after', sa.Integer(), nullable=True),
    sa.Column('ufc_fights_before', sa.Integer(), nullable=True),
    sa.Column('days_since_last_fight', sa.Integer(), nullable=True),
    sa.CheckConstraint("outcome IN ('win', 'loss', 'draw', 'nc')"),
    sa.ForeignKeyConstraint(['bout_id'], ['bouts.bout_id'], ),
    sa.ForeignKeyConstraint(['fighter_id'], ['fighters.fighter_id'], ),
    sa.PrimaryKeyConstraint('bout_id', 'fighter_id')
    )
    op.create_table('judge_scores',
    sa.Column('bout_id', sa.String(length=16), nullable=False),
    sa.Column('fighter_id', sa.String(length=16), nullable=False),
    sa.Column('judge1_score', sa.Integer(), nullable=True),
    sa.Column('judge2_score', sa.Integer(), nullable=True),
    sa.Column('judge3_score', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['bout_id'], ['bouts.bout_id'], ),
    sa.ForeignKeyConstraint(['fighter_id'], ['fighters.fighter_id'], ),
    sa.PrimaryKeyConstraint('bout_id', 'fighter_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('judge_scores')
    op.drop_table('bout_participants')
    op.drop_table('bouts')
    op.drop_table('pre_ufc_bouts')
    op.drop_table('events')
    op.drop_table('promotions')
    op.drop_table('fighters')
    # ### end Alembic commands ###
